"""initial

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
try:
    from sqlalchemy.dialects import postgresql
    UUID_TYPE = postgresql.UUID(as_uuid=True)
except ImportError:
    UUID_TYPE = sa.String(36)  # SQLite fallback

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', UUID_TYPE, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_email'), 'professionals', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', UUID_TYPE, nullable=False),
    sa.Column('professional_id', UUID_TYPE, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cpf_last4', sa.String(), nullable=True),
    sa.Column('cpf_encrypted', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_professional_id'), 'patients', ['professional_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', UUID_TYPE, nullable=False),
    sa.Column('patient_id', UUID_TYPE, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('adherence', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('recommendation_template_diet', sa.String(), nullable=True),
    sa.Column('recommendation_template_training', sa.String(), nullable=True),
    sa.Column('recommendation_template_lifestyle', sa.String(), nullable=True),
    sa.Column('next_return_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_patient_id'), 'checkins', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_patient_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_patients_professional_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_professionals_email'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###

